### ISSUE TITLE
Accept / decline modal close option in header

### ISSUE THREAD

**Issue by Chris-Shields** [fluenttechnology/northstar#11]
If you wouldn't mind adding the ability to close the accept / decline modal to it's header please, that would be appreciated. This should cause the sidebar to slide closed. 

![image](https://user-images.githubusercontent.com/31107754/45021833-7bfb9380-b02a-11e8-8527-bff33118a112.png)

**Comment by goofballLogic** [comment]
this should follow the pattern in the outstanding pull request: https://github.com/fluenttechnology/northstar/pull/9 is that ok?

**Comment by goofballLogic** [comment]
pattern accepted in #9
