### ISSUE TITLE
Documents data/styling?

### ISSUE THREAD

**Issue by goofballLogic** [fluenttechnology/northstar#18]
PDF styles documents like this:

![image](https://user-images.githubusercontent.com/910448/45149784-47224480-b1c2-11e8-9b50-7abcc8811ee4.png)

and the data I provided looks like this:

![image](https://user-images.githubusercontent.com/910448/45149912-8ea8d080-b1c2-11e8-9724-9bd25fa31dda.png)

but it's currently styled like this:

![image](https://user-images.githubusercontent.com/910448/45149869-7769e300-b1c2-11e8-97a9-cb56f8acae07.png)

1. "content-type-name" was provided for display purposes rather than "type"
2. "content-type" was provided so that we could choose icons matching the content type. Is this needed? If not I'd like to remove it from the underlying data
3. Should I remove "when" from the underlying data - looks like it's not used?

**Comment by Chris-Shields** [comment]
I've created an inconsistency by doing the sidebar artwork on the fly, I'll normalise the design to utilise the icons.

**Comment by Chris-Shields** [comment]
I've kept the sidebar styling a little different from the PDF to make them more call to action like, but taken more of the flavour than before. I think when should be dropped as it was only really relevant to a GM user. Timestamps on documents aren't particularly useful to reviewers.

**Comment by goofballLogic** [comment]
It appears that we still need "when" for the Application view rendering of the uploaded documents so I should probably keep it in

![image](https://user-images.githubusercontent.com/910448/45345311-ea49d400-b59d-11e8-8654-bb031ef41ed7.png)

**Comment by goofballLogic** [comment]
Closing this as it appears we have resolved the questions.
