### ISSUE TITLE
anchor tag for menu button

### ISSUE THREAD

**Issue by goofballLogic** [fluenttechnology/northstar#2]
There may be a good reason for this but, why are we using an anchor tag for a menu toggle button?

https://github.com/fluenttechnology/northstar/blob/master/src/App.js#L26

```
<a aria-role="combo" id="user-profile-menu" className="user-profile" aria-haspopup="true" aria-expanded="false">
```

**Comment by Chris-Shields** [comment]
I took this from a bootstrap example, it's capable of being both a button or a link but yeah, should really be a button to stick with the buttons interact, links navigate practice.

**Comment by Chris-Shields** [comment]
I'll change that now.

**Comment by Chris-Shields** [comment]
successfully buttonised. Required a few extra lines of CSS to override chrome's default button styles.

**Comment by Chris-Shields** [comment]
Tested in Safari, Chrome, Firefox (mac) so far

**Comment by goofballLogic** [comment]
does this mean you have a menu inside a button?

**Comment by goofballLogic** [comment]
"What would the unenhanced version of this look like?"

**Comment by Chris-Shields** [comment]
If we were to unenhance these then the options would have to exist on the header. It's possible to move the menu outside the button and have it sit beside in a non styled / non js version, however this would mean the enhanced will be reliant in JS to show hide.

**Comment by goofballLogic** [comment]
Some options off the top of my head (others exist):

| # | Unenhanced | Enhanced |
|---|---|---|
|  1 | Profile, name and role are a link to another "menu" screen | Link is intercepted and the target is loaded into the desired position |
| 2 | Profile, name and role are a button within a form which, when submitted transitions the screen into a state where the menu is showing | Submit is intercepted, screen changes state client-side |
| 3 | The whole menu is shown as a `nav` | Javascript hides the "drop-down" options and reveals them on click |

**Comment by goofballLogic** [comment]
@Chris-Shields shall i take this on to help?

**Comment by Chris-Shields** [comment]
@goofballLogic that would be appreciated.
