### ISSUE TITLE
aria-role invalid aria attribute?

### ISSUE THREAD

**Issue by goofballLogic** [fluenttechnology/northstar#3]
I don't believe that aria-role is a valid attribute name:
https://github.com/fluenttechnology/northstar/blob/master/src/App.js#L26

**Comment by Chris-Shields** [comment]
thanks, fixed.

**Comment by goofballLogic** [comment]
https://github.com/fluenttechnology/northstar/blob/master/src/App.js#L27

BTW: create-react-app tells you about these in the console logs

**Comment by Chris-Shields** [comment]
also a merge conflict.

**Comment by Chris-Shields** [comment]
https://github.com/fluenttechnology/northstar/blob/master/src/App.js#L27
