### ISSUE TITLE
Vertical divider doesn't extend full height of screen

### ISSUE THREAD

**Issue by goofballLogic** [fluenttechnology/northstar#33]
http://recordit.co/lsulNRKiTt

vertical bar doesn't extend to the bottom of the screen on dashboard when you scroll down

![image](https://user-images.githubusercontent.com/910448/45703864-667b8300-bb6d-11e8-8332-bfb4a503d8e7.png)

**Comment by Chris-Shields** [comment]
Picked up on this too. The sidebar did not have the same height logic as the left panel. Applied same logic

![image](https://user-images.githubusercontent.com/31107754/45815518-d9513f00-bcd0-11e8-9e34-b28e6fd6a4bc.png)

**Comment by Chris-Shields** [comment]
Ended up using a fixed position :before.

- Inside flexbox the height can never be more than 100% of the parent, our parent was a fixed 100vh for inner scroll
- position absolute did not work as the hight of the scroll is an unknown

**Comment by goofballLogic** [comment]
I'm going to put an item on our project board to review all the CSS once it's all been landed to see if I can see any quick wins for how we have structured it.
