### ISSUE TITLE
Back to Dashboard link doesn't work

### ISSUE THREAD

**Issue by gsloan** [fluenttechnology/northstar#38]
When viewing a review / application form, clicking on the 'Back to Dashboard' link has no effect
![image](https://user-images.githubusercontent.com/5477755/45757854-3d65fb80-bc1c-11e8-8a56-4d0d82f15a01.png)

**Comment by gsloan** [comment]
Follow up question:  Is the 'Back to Dashboard' link really needed, when clicking on the 'Dashboard' link or the FlexiGrant logo at the top both do the same action (I assume)?

**Comment by Chris-Shields** [comment]
@gsloan where is this being tested from that the font awesome icons are not loading? 

Please keep in mind that we are not the user. Our users are very literal thinkers with a history of not doing the obvious, simply because it never said to do so.

**Comment by goofballLogic** [comment]
ok well that _sort of_ makes sense for the top bar (logo + Dashboard) menus, but is there a need for a 3rd "Back to dashboard" link?

The URL is the one we recently moved to: https://fg-rp-1.azurewebsites.net

**Comment by gsloan** [comment]
I agree.  Having the dashboard navigation in the main menu at the top is fine if that menu is going to be extended with more options, but the 'Back to dashboard' link looks redundant, especially with it being positioned so closely to the main navigation.

**Comment by Chris-Shields** [comment]
I have removed the back button until feedback / evidence suggests we need it
