### ISSUE TITLE
img missing alt attribute

### ISSUE THREAD

**Issue by goofballLogic** [fluenttechnology/northstar#4]
https://github.com/fluenttechnology/northstar/blob/master/src/App.js#L28

**Comment by Chris-Shields** [comment]
caught this one whilst adding a new image

**Comment by goofballLogic** [comment]
Looks like this is still a problem: https://github.com/fluenttechnology/northstar/blob/master/src/App.js#L31

BTW, create-react-app tells you about these problems in the console logs

**Comment by Chris-Shields** [comment]
my bad, I was fixing a merge conflict and must have taken yours rather than mine.

**Comment by Chris-Shields** [comment]
![image](https://user-images.githubusercontent.com/31107754/44989471-da226b00-af85-11e8-8161-b3f85904fe51.png)

**Comment by Chris-Shields** [comment]
it's definitely there!
