### ISSUE TITLE
The textarea for reason to decline a review gets cut off when scrolling to the bottom of the modal

### ISSUE THREAD

**Issue by gsloan** [fluenttechnology/northstar#55]
![image](https://user-images.githubusercontent.com/5477755/46287605-ff9d9700-c57a-11e8-9959-781db5ca329c.png)

**Comment by gsloan** [comment]
The wording for that textbox label is also a bit strange, asking the main reason for declining as if the reason given above doesn't count.

**Comment by Chris-Shields** [comment]
Updated decline modal
